# Generated by Django 6.0.4 on 2026-04-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lingua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=50)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                            ("Nativo", "Nativo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("certificado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("erros_encontrados", models.TextField(blank=True, null=True)),
                ("uso_ia", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="grau",
            field=models.CharField(default="Licenciatura", max_length=50),
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("hard", "Hard Skill"), ("soft", "Soft Skill")],
                        max_length=10,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("iniciante", "Iniciante"),
                            ("intermedio", "Intermédio"),
                            ("avancado", "Avançado"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("autores", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("orientador", models.CharField(max_length=100)),
                ("ranking", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("ects", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("icone", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("github_link", models.URLField(blank=True, null=True)),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("conceitos_aplicados", models.TextField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link_pagina", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "ucs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professores",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
