# Generated by Django 6.0.4 on 2026-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_lingua_makingof_tecnologia_licenciatura_grau_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="area",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
