# Generated by Django 6.0.4 on 2026-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tfc_area_tfc_imagem_url_tfc_link_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="participantes",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("linguagem", "Linguagem de Programação"),
                    ("framework", "Framework"),
                    ("ferramenta", "Ferramenta"),
                    ("biblioteca", "Biblioteca"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="ano_letivo",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
